os: linux

services:
 - docker

# install:
#  - docker login -u $USERNAME -p $PASSWORD 

# script:
#   - docker image build -t $USERNAME/python-app .
script:
  - echo "Hello World"

deploy:
  provider: heroku
  app: flask-app-sunil
  api_key: $HEROKU_API_KEY
